### ISSUE TITLE
add repo url not found: Error 404

### ISSUE THREAD

**Issue by fri-it2** [perfsonar/ansible-role-perfsonar-installer#2]
Hello.
I run playbook with role ansible-role-perfsonar-installer.

Url http://software.internet2.edu/rpms/el7/x86_64/main/RPMS/perfSONAR-repo-0.8-1.noarch.rpm: Error 404: Not found
```
# yum install http://software.internet2.edu/rpms/el7/x86_64/main/RPMS/perfSONAR-repo-0.8-1.noarch.rpm
- name: (RedHat) Add perfSONAR repository
  tags: [ 'ps::install' ]
  yum:
    name: http://software.internet2.edu/rpms/el7/x86_64/main/RPMS/perfSONAR-repo-0.8-1.noarch.rpm
    state: present
```
Best regards,
Tadeja
